version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: railways
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
  
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
  
  bot:
    container_name: bot
    build: 
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - webnet


volumes:
  pgdata:

networks:
  webnet: